"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabase";
type Video={id:number;title:string|null;description:string|null;video_url:string;thumbnail_url:string|null;views_count:number;creator_id:string;profiles?:{username:string|null}|null};
export default function Home(){const router=useRouter();const [videos,setVideos]=useState<Video[]>([]),[active,setActive]=useState(0),[loading,setLoading]=useState(true),[userId,setUserId]=useState<string|null>(null),[liked,setLiked]=useState<Record<number,boolean>>({}),[likeCounts,setLikeCounts]=useState<Record<number,number>>({});
useEffect(()=>{let mounted=true;(async()=>{if(!supabase){setLoading(false);return}const [{data,error},{data:{user}}]=await Promise.all([supabase.from("craken_videos").select("id,title,description,video_url,thumbnail_url,views_count,creator_id,profiles(username)").eq("visibility","public").order("created_at",{ascending:false}),supabase.auth.getUser()]);if(!error&&mounted){const list=(data??[]) as Video[];setVideos(list);setUserId(user?.id??null);if(list.length){const ids=list.map(v=>v.id);const {data:likes}=await supabase.from("craken_likes").select("video_id,user_id").in("video_id",ids);const counts:Record<number,number>={};const mine:Record<number,boolean>={};(likes??[]).forEach((l:{video_id:number;user_id:string})=>{counts[l.video_id]=(counts[l.video_id]??0)+1;if(user?.id===l.user_id)mine[l.video_id]=true});setLikeCounts(counts);setLiked(mine)}}setLoading(false)})();return()=>{mounted=false}},[]);
const toggleLike=async(id:number,e:React.MouseEvent)=>{e.stopPropagation();if(!supabase||!userId){router.push("/auth");return}const isLiked=!!liked[id];if(isLiked){const {error}=await supabase.from("craken_likes").delete().eq("video_id",id).eq("user_id",userId);if(!error){setLiked(p=>({...p,[id]:false}));setLikeCounts(p=>({...p,[id]:Math.max(0,(p[id]??1)-1)}))}}else{const {error}=await supabase.from("craken_likes").insert({video_id:id,user_id:userId});if(!error){setLiked(p=>({...p,[id]:true}));setLikeCounts(p=>({...p,[id]:(p[id]??0)+1}))}}};
const items=videos.length?videos:[{id:0,title:"Aucune vidéo publiée",description:"Craken-type est connecté à sa base. Connecte-toi pour publier la première vidéo.",video_url:"",thumbnail_url:null,views_count:0,creator_id:""} as Video];
return <main className="app"><header><div className="logo">Craken<span>-type</span></div><button className="login" onClick={()=>router.push("/auth")}>Se connecter</button></header><section className="feed">{loading?<div className="empty">Chargement du fil…</div>:items.map((v,i)=><article className={"video "+(i===active?"active":"")} key={v.id} onClick={()=>setActive(i)}><div className="videoBg">{v.video_url?<video src={v.video_url} poster={v.thumbnail_url??undefined} autoPlay={i===active} muted loop playsInline/>:<div className="play">▶</div>}</div><div className="info"><b>@{v.profiles?.username||"craken"}</b><h2>{v.title??"Sans titre"}</h2><p>{v.description??""}</p><div className="tags">#CrakenType #Créateurs</div></div><div className="actions"><button onClick={e=>toggleLike(v.id,e)} className={liked[v.id]?"liked":""}>♥<small>{likeCounts[v.id]??0} J’aime</small></button><button onClick={e=>e.stopPropagation()}>◌<small>Commenter</small></button><button onClick={e=>e.stopPropagation()}>↗<small>Partager</small></button></div></article>)}</section><nav><button>⌂<span>Accueil</span></button><button>⌕<span>Découvrir</span></button><button className="create" onClick={()=>router.push("/upload")}>＋</button><button>♡<span>Activité</span></button><button onClick={()=>router.push("/auth")}>◉<span>Profil</span></button></nav></main>}